IMDb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import  settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndesTemplateView.as_view(),name = 'index'),
    path('lancamentos/',views.LancamentosTemplateView.as_view(), name = 'lancamentos'),
    path('cartaz/',views.CartazTemplatesViews.as_view(), name = 'cartaz'),
    path('accounts/', include('accounts.urls')),
    path('documentary/', include('documentary.urls', namespace = 'documentary')),
    path('serie/', include('serie.urls', namespace = 'serie')),
    path('movie/',include('movie.urls', namespace = 'movie')),
    path('actor/', include('actor.urls', namespace = 'actor')),

    #------------------ Dashboard --------------------------------------------------------

    path('dashboard/', include('dashboard.urls', namespace = 'dashboard')),


    #------------------------ MANAGEMENT --------------------------
    path('',include('management.urls', namespace = 'management')),

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

documentary/urls.py
from django.urls import path
from . import views



app_name = 'documentary'



urlpatterns = [


    path('manager/', views.documentary_manager, name = 'manager'),
    path('search/', views.documentary_search, name = 'search'),
    path('<imdb_id>/details/', views.documentary_details, name = 'details'),

    
]

documentary/models.py
from django.db import models
from actor.models import Actor
from django.utils.text import slugify
import requests
from io import BytesIO
from django.core import files
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField 
from multiselectfield import MultiSelectField
from django.conf import settings
from django.utils import timezone
# Create your models here.

class Genre(models.Model):
	title = models.CharField(max_length=25)
	slug = models.SlugField(null=False, unique=True)

	def get_absolute_url(self):
		return reverse('genres', args=[self.slug])

	def __str__(self):
		return self.title

	def save(self, *args, **kwargs):
		if not self.slug:
			self.title.replace(" ", "")
			self.slug = slugify(self.title)
		return super().save(*args, **kwargs)

class D_Rating(models.Model):
	source = models.CharField(max_length=50)
	rating = models.CharField(max_length=10)

	def __str__(self):
		return self.source

class Documentary(models.Model):


	STATUS_CHOICES = (
                        ('cartaz','Cartaz'),
                        ('em breve','Em Breve'),
                        ('lançamento','Lançamento'),
                        ('geral', 'Geral'),
                        ('novo','Novo')
                      )
	Title = models.CharField(max_length=200)
	Year = models.CharField(max_length=25, blank=True)
	Publish = models.DateTimeField(default=timezone.now,  blank=True)
	Created = models.DateTimeField(auto_now_add=True,  blank=True) 
	Updated = models.DateTimeField(auto_now=True,  blank=True)
	Status = models.CharField(max_length = 140, choices = STATUS_CHOICES , default = 'geral',  blank=True)  
	Popularity = models.IntegerField()
	Rated = models.CharField(max_length=10, blank=True)
	Released = models.CharField(max_length=25, blank=True)
	Runtime = models.CharField(max_length=25, blank=True)
	Genre = models.ManyToManyField(Genre, blank=True)
	Director = models.CharField(max_length=100, blank=True)
	Writer = models.CharField(max_length=300, blank=True)
	Actors = models.ManyToManyField(Actor, blank=True)
	Plot = models.CharField(max_length=900, blank=True)
	Language = models.CharField(max_length=300, blank=True)
	Country = models.CharField(max_length=100, blank=True)
	Awards = models.CharField(max_length=250, blank=True)
	Poster = models.ImageField(upload_to='movies', blank=True)
	Poster_url = models.URLField(blank=True)
	Rating = models.ManyToManyField(D_Rating, blank=True)
	Metascore = models.CharField(max_length=5, blank=True)	
	imdbRating = models.CharField(max_length=5, blank=True)
	imdbCount = models.CharField(max_length=100, blank=True)
	imdbVotes = models.CharField(max_length=100, blank=True)
	imdbID = models.CharField(max_length=100, blank=True)	
	Filmes_views = models.IntegerField(default=0,  blank=True)
	Video = models.IntegerField(default=0,  blank=True)
	Trailer = models.CharField(max_length=100, blank=True)
	Watched = models.IntegerField( default=0,  blank=True)  
	Type = models.CharField(max_length=10, blank=True)
	DVD = models.CharField(max_length=25, blank=True)
	BoxOffice = models.CharField(max_length=25, blank=True)
	Production = models.CharField(max_length=100, blank=True)
	Website = models.CharField(max_length=150, blank=True)
	totalSeasons = models.CharField(max_length=3, blank=True)
	totalEpisodes =  models.CharField(max_length=3, blank=True)

	def __str__(self):
		return self.Title

	def save(self, *args, **kwargs):
		if self.Poster == '' and self.Poster_url !='':
			resp = requests.get(self.Poster_url)
			pb = BytesIO()
			pb.write(resp.content)
			pb.flush()
			file_name = self.Poster_url.split("/")[-1]
			self.Poster.save(file_name, files.File(pb), save=False)

		return super().save(*args, **kwargs)

	def __str__(self):
		return self.Title

	def save(self, *args, **kwargs):
		if self.Poster == '' and self.Poster_url !='':
			resp = requests.get(self.Poster_url)
			pb = BytesIO()
			pb.write(resp.content)
			pb.flush()
			file_name = self.Poster_url.split("/")[-1]
			self.Poster.save(file_name, files.File(pb), save=False)

		return super().save(*args, **kwargs)


RATE_CHOICES = [
   	(1, '1 - Lixo'),
    (2, '2 - Horrível'),
    (3, '3 - Terrível'),
    (4, '4 - Ruim'),
    (5, '5 - OK'),
    (6, '6 - Watchable'),
    (7, '7 - Bom'),
    (8, '8 - Muito bom'),
    (9, '9 - Perfeito'),
    (10, '10 - Obra-prima '), 

]


class D_Review(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name = "documentary", on_delete=models.CASCADE)
	documentary = models.ForeignKey(Documentary, on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now_add=True)
	text = models.TextField(max_length=3000, blank=True)
	rate = models.PositiveSmallIntegerField(choices=RATE_CHOICES)
	likes = models.PositiveIntegerField(default=0)
	unlikes = models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.user.username

class D_Likes(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL , on_delete=models.CASCADE, related_name='documentary_user_like')
	type_like = models.PositiveSmallIntegerField()
	review = models.ForeignKey(D_Review, on_delete=models.CASCADE, related_name='documetary_review_like')

documentary/forms.py
from django import forms
from .models import Documentary





class DocumentaryForm(forms.ModelForm):

    class Meta:
        model = Documentary
        fields = ('__all__')

documentary/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.utils.text import slugify
from django.core.paginator import Paginator
from django.urls import reverse
from django.db.models import Avg
from .models import Documentary, D_Review, D_Likes, Genre, D_Rating
from actor.models import Actor
from django.contrib.auth.models import User
from movie.forms import RateForm
import requests




def documentary_manager(request):
	documentary = Documentary.objects.all()

	paginator = Paginator(documentary, 9) # 3 posts in each page
	page = request.GET.get('page')
	try:
		paginas = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer deliver the first page
		paginas = paginator.page(1)
	except EmptyPage:
		# If page is out of range deliver last page of results
		paginas = paginator.page(paginator.num_pages)


	return render(request, 'documentary/index.html',{'documentary':documentary, 'page':page,'paginas':paginas} )



# Create your views here.
def documentary_search(request):
	query = request.GET.get('search')

	if query:
		url = 'http://www.omdbapi.com/?apikey=2d2a4142&s=' + query
		response = requests.get(url)
		documentary = response.json()
		

		return render(request, 'documentary/search.html',{'query': query,'documentary': documentary})

	return render(request, 'documentary/search.html')



def documentary_details(request, imdb_id):

	if Documentary.objects.filter(imdbID=imdb_id).exists():
		documentary = Documentary.objects.get(imdbID=imdb_id)
		reviews = D_Review.objects.filter(documentary=documentary)
		reviews_avg = reviews.aggregate(Avg('rate'))
		reviews_count = reviews.count()
		our_db = True

		context = {
			'documentary': documentary,
			'reviews': reviews,
			'reviews_avg': reviews_avg,
			'reviews_count': reviews_count,
			'our_db': our_db,
		}

	else:
		url = 'http://www.omdbapi.com/?apikey=2d2a4142&i=' + imdb_id
		response = requests.get(url)
		documentary = response.json()

		#Inject to our database bellow:

		rating_objs = []
		genre_objs = []
		actor_objs = []

		#For the actors
		actor_list = [x.strip() for x in documentary['Actors'].split(',')]

		for actor in actor_list:
			a, created = Actor.objects.get_or_create(name=actor)
			actor_objs.append(a)

		#For the Genre or categories
		genre_list = list(documentary['Genre'].replace(" ", "").split(','))

		for genre in genre_list:
			genre_slug = slugify(genre)
			g, created = Genre.objects.get_or_create(title=genre, slug=genre_slug)
			genre_objs.append(g)

		#For the Rate
		for rate in documentary['Ratings']:
			r, created = D_Rating.objects.get_or_create(source=rate['Source'], rating=rate['Value'])
			rating_objs.append(r)

		if documentary['Type'] == 'movie':
			m, created = Documentary.objects.get_or_create(
				Title=documentary['Title'],
				Year=documentary['Year'],
				Publish = '2001-01-01 00:00:00', 
				Created = '2001-01-01 00:00:00', 
    			Updated = '2001-01-01 00:00:00', 		
				Status =  'geral', 
				Popularity = 0,
				Rated=documentary['Rated'],
				Released=documentary['Released'],
				Runtime=documentary['Runtime'],
				Director=documentary['Director'],
				Writer=documentary['Writer'],
				Plot=documentary['Plot'],
				Language=documentary['Language'],
				Country=documentary['Country'],
				Awards=documentary['Awards'],
				Poster_url=documentary['Poster'],
				Metascore=documentary['Metascore'],				
				imdbRating=documentary['imdbRating'],
				imdbCount = '0', 
				imdbVotes=documentary['imdbVotes'],
				imdbID=documentary['imdbID'],
				Filmes_views = 0,
				Video = 0,
				Trailer = '',
				Watched  = 0,
				Type = documentary['Type'],
				DVD = " ",
				BoxOffice = " ",
				Production= " ",
				Website = " ",
                totalSeasons =  0,
				totalEpisodes =  " ",
				)
			m.Genre.set(genre_objs)
			m.Actors.set(actor_objs)
			m.Rating.set(rating_objs)

		else:
			m, created = Documentary.objects.get_or_create(
				Title=documentary['Title'],
				Year=documentary['Year'],
				Publish = '2001-01-01 00:00:00', 
				Created = '2001-01-01 00:00:00', 
    			Updated = '2001-01-01 00:00:00', 		
				Status =  'geral', 
				Popularity = 0,
				Rated=documentary['Rated'],
				Released=documentary['Released'],
				Runtime=documentary['Runtime'],
				Director=documentary['Director'],
				Writer=documentary['Writer'],
				Plot=documentary['Plot'],
				Language=documentary['Language'],
				Country=documentary['Country'],
				Awards=documentary['Awards'],
				Poster_url=documentary['Poster'],
				Metascore=documentary['Metascore'],				
				imdbRating=documentary['imdbRating'],
				imdbCount = '0', 
				imdbVotes=documentary['imdbVotes'],
				imdbID=documentary['imdbID'],
				Filmes_views = 0,
				Video = 0,
				Trailer = '',
				Watched  = 0,
				Type = documentary['Type'],
				DVD = " ",
				BoxOffice = " ",
				Production= " ",
				Website = " ",
                totalSeasons =  0,
				totalEpisodes =  " ",
				)

			m.Genre.set(genre_objs)
			m.Actors.set(actor_objs)
			m.D_Ratings.set(rating_objs)


		for actor in actor_objs:
			actor.documentarys.add(m)
			actor.save()

		m.save()
		our_db = False

		context = {
			'movie_data': movie_data,
			'our_db': our_db,
		}

	template = loader.get_template('documentary/details.html')

	return HttpResponse(template.render(context, request))


def genres(request, genre_slug):
	genre = get_object_or_404(Genre, slug=genre_slug)
	movies = Documentary.objects.filter(Genre=genre)

	#Pagination
	paginator = Paginator(movies, 9)
	page_number = request.GET.get('page')
	movie_data = paginator.get_page(page_number)

	context = {
		'movie_data': movie_data,
		'genre': genre,
	}


	template = loader.get_template('genre.html')

	return HttpResponse(template.render(context, request))


def addMoviesToWatch(request, imdb_id):
	movie = Documentary.objects.get(imdbID=imdb_id)
	user = request.user
	profile = Profile.objects.get(user=user)

	profile.to_watch.add(movie)

	return HttpResponseRedirect(reverse('movie-details', args=[imdb_id]))

def addMoviesWatched(request, imdb_id):
	movie = Documentary.objects.get(imdbID=imdb_id)
	user = request.user
	profile = Profile.objects.get(user=user)

	if profile.to_watch.filter(imdbID=imdb_id).exists():
		profile.to_watch.remove(movie)
		profile.watched.add(movie)
		
	else:
		profile.watched.add(movie)

	return HttpResponseRedirect(reverse('movie-details', args=[imdb_id]))


def Rate(request, imdb_id):
	movie = Documentary.objects.get(imdbID=imdb_id)
	user = request.user

	if request.method == 'POST':
		form = RateForm(request.POST)
		if form.is_valid():
			rate = form.save(commit=False)
			rate.user = user
			rate.movie = movie
			rate.save()
			return HttpResponseRedirect(reverse('movie-details', args=[imdb_id]))
	else:
		form = RateForm()

	template = loader.get_template('rate.html')

	context = {
		'form': form, 
		'movie': movie,
	}

	return HttpResponse(template.render(context, request))

documentary/templates/documentary/created.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% load bootstrap4 %}


{% block management %}
<div class="section-header">
    <div class="slider-outer">
        <div class="slider-inner">
            <div class="  statistic fron active" data-slider="1">
                <i class="fas fa-laptop-code"></i>
                <div class="statistic-title">Filmes</div>
                <h2 class="title-statistic-h2">Add +</h2>
                              
            </div>
        </div>
    </div>
</div>

  <div class="section-body">
      	
			<div class="dashboard-container">
				
                <h2 class="section-title">Adicionar Novos Filmes</h2>
                <p class="section-lead">
                    Skrn - Site completo com filmes lançamentos, séries em HD online dublado e legendado em HD e FullHD. 
                </p>

				<div class="row">
								
					<div class="col-12 col-md-6 col-lg-6">
						<div class="card">
						  <div class="card-header">
							<h4>Formulário</h4>
						  </div>
						  <div class="card-body">
							<div class="alert alert-info">
							  <b>Nota!</b> lançamentos de um novo filme em HD online em HD e FullHD.
							</div>            
							{# Display a form #}
							<form style = "margin-left:36px; margin-right:36px;"  action="." method="post" >
							<div style = "position:relative; right:40px;" class="card-header">
									<h4>Validação do dados  do Filme</h4>
									</div>
								{% csrf_token %}
								{% bootstrap_form form %}
								{% buttons %}
									<button type="submit" class="btn btn-primary">Criar</button>
								{% endbuttons %}
								  
							</div>
						   
						 
						</div>
					 
			  
						  </div>
					 
				
				</div><!-- close .row -->
									
			</div><!-- close .dashboard-container -->
  </div>

{% endblock %}

documentary/templates/documentary/delete.html
{% extends 'dashboard/base.html' %}
{% load static %}


{% block management %}
<div class="section-header">
    <div class="slider-outer">
        <div class="slider-inner">
            <div class="  statistic fron active" data-slider="1">
                <i class="far fa-trash-alt"></i>
				
                <div class="statistic-title">Séries</div>
                <h2 class="title-statistic-h2">Delete</h2>
                              
            </div>
        </div>
    </div>
</div>

  <div class="section-body">
    <h2 class="section-title">Deletar o documentário <span style="color: brown; font-size: 20px;">{{ documentary.Title }}</span> </h2>
    <div class="row">    
    
      <div class="col-12 col-md-12 col-sm-12">
        <div class="card">
          <div class="card-header">
            <h4>Ops...., Tem certeza que deseja deletar esse documentário</h4>
          </div>
          <div class="card-body">
            <div class="empty-state" data-height="400">
              <div class="empty-state-icon bg-danger">
                <i class="far fa-trash-alt"></i>
              </div>
              <h2>Este Documentário será apagado</h2>
              <p class="lead">
                As informações sobre <strong>{{ documentary }}</strong>, serão apagado do nossos servidores. (Código: <a href="#" class="bb">{{documentary.imdbID}}</a>)
              </p>
              <a href="#" class="btn btn-success mt-4">Comfirmar</a>
              <a href="{% url 'documentary:details' documentary.imdbID %}" class="mt-4 bb">Cancel</a>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            <h4>Not Found</h4>
          </div>
          <div class="card-body">
            <div class="empty-state" data-height="600">
              <img class="img-fluid" src="../assets/img/drawkit/drawkit-nature-man-colour.svg" alt="image">
              <h2 class="mt-0">Looks like you got lost</h2>
              <p class="lead">
                We can't find the path you're looking for, check the path again and try again.
              </p>
              <a href="#" class="btn btn-warning mt-4">Try Again</a>
              <a href="#" class="mt-4 bb">Need Help?</a>
            </div>
          </div>
        </div>
      </div> 		
    </div>
  </div>

{% endblock %}

documentary/templates/documentary/details.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block management %}
<div class="section-header">
    <div class="slider-outer">
        <div class="slider-inner">
            <div class="  statistic fron active" data-slider="1">
                <i class="fas fa-info"></i>
				
                <div class="statistic-title">Documentários</div>
                <h2 class="title-statistic-h2">Informações</h2>
                              
            </div>
        </div>
    </div>
</div>
    <div class="section-body">      	
		<div class="dashboard-container">
            <h2 class="section-title">Informações do Filmes: <span>{{ object }}</span> </h2>
            <p class="section-lead">
                Skrn - Site completo com filmes lançamentos, séries em HD online dublado e legendado em HD e FullHD. 
            </p>
            <div class="row">
                <div class="col-12 col-md-4 col-lg-4">
                  <article class="article article-style-">
                    <div class="article-header">
                    {% if our_db is True%}
                    <div  class="article-image" data-background="{{ documentary.Poster_url }}"></div>
                    {% else %}
                    <div  class="article-image" data-background="{{ documentary.Poster }}"></div>
                    {% endif %}                  
                    </div>                   
                  </article>
                </div>
                <div class="col-12 col-sm-12 col-lg-7">
                    <div class="card author-box card-warning">
                      <div class="card-body">                        
                        <div >
                          <div class="author-box-name">
                            <a href="#">{{ documentary.Title }}</a>
                        </div>
                        <div class="author-box-job"><li><span>Tipo:</span> <a href="#">{{ documentary.Type }}</a></li></div>
                        <div class="author-box-job"><li><span>Descrição:</span> <a href="#">{{ documentary.Plot }}</a></li></div>
                        <div class="author-box-job"><li><span>Ano de Lançamento:</span> <a href="#">{{ documentary.Year }}</a></li></div>
                        <div class="author-box-job"><li><span>Avaliado:</span> <a href="#">{{ documentary.Rated }}</a></li></div>
                        <div class="author-box-job"><li><span>Data de Lançamento:</span> <a href="#">{{ documentary.Released }}</a></li></div>
                        <div class="author-box-job"><li><span>Runtime:</span> <a href="#">{{ documentary.Runtime }}</a></li></div>
                        <div class="author-box-job"><li><span>Popularidade:</span> <a href="#">{{ documentary.Popularity }}</a></li></div>

          
                          {% if our_db is True %}
                          <div class="author-box-job"><li ><span>Categorias:{% for genre in documentary.Genre.all %}</span> <a href="#">Ação,</a> <a href="#">{{ genre }},</a>{% endfor %}</li></div>
                          {% else %}
                          <div class="author-box-job"><li ><span>Categorias:</span><a href="#">{{ documentary.Genre }},</a></li></div>
                          {% endif %}
                          <div class="author-box-job"><li><span>Diretores:</span> <a href="#">{{ documentary.Director }}</a></li></div>
                          <div class="author-box-job"><li><span>Escritor(a):</span> <a href="#">{{ documentary.Writer }}</a></li></div>
                          {% if our_db is True %}
                          <div class="author-box-job"><li><span>Atores:{% for actor in documentary.Actors.all %}</span> <a href="{% url 'actor:details' actor.slug %}">{{ actor }}</a>{% endfor %}</li></div>
                          {% else %}
                          <div class="author-box-job"><li><span>Atores:</span> <a href="">{{ documentary.Actors }}</a></li></div>
                          {% endif %}
                          <div class="author-box-job"><li><span>Linguagem:</span> <a href="#">{{ documentary.Language }}</a></li></div>
                          <div class="author-box-job"><li><span>País:</span> <a href="#">{{ documentary.Country }}</a></li></div>
                          <div class="author-box-job"><li><span>Prêmios:</span> <a href="#">{{ documentary.Awards }}</a></li></div>
                         
                                                  
                            <br>                                               
                          <ul class="list-unstyled user-progress list-unstyled-border list-unstyled-noborder">                                                                          
                             <li class="media">
                                {% if  our_db is True %}
                                {% for documentary in documentary.Ratings.all %}   
                                {% if documentary.source == 'Internet Movie Database' %}                 
                                <div class="media-items">
                                  <div class="media-item">
                                    <div class="media-value">{{ documentary.rating }}</div>
                                    <div class="media-label">{{ documentary.source }} </div>                                   
                                </div>
                                  </div>
                                  {% elif movie.source == 'Rotten Tomatoes' %} 
                                  <div class="media-items"> 
                                  <div class="media-item">
                                    <div class="media-value">{{ documentary.rating }}</div>
                                    <div class="media-label">{{ documentary.source }} </div>
                                  </div>
                                  </div>
                                  {% else %} 
                                 <div class="media-items"> 
                                  <div class="media-item">
                                    <div class="media-value">{{ documentary.rating }}</div>
                                    <div class="media-label">{{ documentary.source }} </div>
                                  </div>
                                 </div>
                                 {% endif %}
                                 {% endfor %}
                                 {% else %}
                        </li>    
                            <li class="media">                            
                                <div class="media-body">
                                    <img src="" alt="">
                                  <div class="media-title">{{ documentary.Ratings.0.Source }} </div>
                                  <div class="text-job text-muted">{{ documentary.Ratings.0.Value }}</div>
                                </div>
                                <div class="media-progressbar">
                                  <div class="progress-text"></div>                                 
                                </div>                             
                              </li> 
                              <li class="media">                            
                                <div class="media-body">
                                    <img src="" alt="">
                                  <div class="media-title">{{ documentary.Ratings.1.Source }} </div>
                                  <div class="text-job text-muted">{{ documentary.Ratings.1.Value }}</div>
                                </div>
                                <div class="media-progressbar">
                                  <div class="progress-text"></div>                                 
                                </div>                             
                              </li> 
                              <li class="media">                            
                                <div class="media-body">
                                    <img src="" alt="">
                                  <div class="media-title">{{ documentary.Ratings.2.Source }} </div>
                                  <div class="text-job text-muted">{{ documentary.Ratings.2.Value }}</div>
                                </div>
                                <div class="media-progressbar">
                                  <div class="progress-text"></div>                                 
                                </div>                             
                              </li> 
                            {% endif %}                           
                          </ul>                          
                          <div class="author-box-job"><li><span>Box Office:</span> <a href="#">{{ documentary.BoxOffice }}</a></li></div>
                          <div class="author-box-job"><li><span>imdb Votes:</span> <a href="#">{{ documentary.omdbVotes }}</a></li></div>
                          <div class="author-box-job"><li><span>Production:</span> <a href="#">{{ documentary.Production }}</a></li></div>
                          <div  class=" mt-sm-0 mt-3 btn-movie ">
                            <a  href="#" class="btn"><i class="far fa-edit"></i></a>
                            <a href="#" class="btn"><i class="far fa-trash-alt"></i></a>
                          </div>                          
                        </div>
                      </div>
                    </div>                   
                  </div>            
              </div>			
	    </div><!-- close .row -->									
	</div><!-- close .dashboard-container -->
  

{% endblock %}

documentary/templates/documentary/index.html
{% extends 'dashboard/base.html' %}
{% load static %}


{% block management %}
<div class="section-header">
    <div class="slider-outer">
        <div class="slider-inner">
            <div class="  statistic fron active" data-slider="1">
                <i class="fab fa-dochub"></i>
				
                <div class="statistic-title">management</div>
                <h2 class="title-statistic-h2">Documentário </h2>
                              
            </div>
        </div>
    </div>
</div>

  <div class="section-body">
      	<h2 class="section-title">Lista de documentário adicionado</h2>
            <div class="row">
                {% if documentary_data %}
                {% for documentary in documentary_data %}           
              <div class="col-12 col-md-4 col-lg-4">
                <li class="catalogo-filmes-lista-item">
                    <figure class="filme-poster">
                       <a href="{% url 'documentary:details' documentary.imdbID %}"><img src="{{ documentary.Poster_url}} alt="img" /></a> 
                        <div class="filme-poster-info">
                            <h3>{{ documentary.Title}}</h3>
                            <a href="{% url 'documentary:details' documentary.imdbID %}" class="filme-poster-link"
                                ><i class="fa fa-play" aria-hidden="true"></i
                            ></a>
                        </div>
                    </figure>

                    <div class="filme-sinopse">
                        <a href="{% url 'documentary:details' documentary.imdbID %}"><h3 class="filme-sinopse-titulo">{{ documentary.Title }}</h3></a>
                        <p class="sinopse-genero">                          
                            <a href="#" class="sinopse-genero-item">{{ documentary.Type }}</a>                          
                        </p>
                        <p class="filme-nota">
                            <i class="fa fa-heart" aria-hidden="true"></i> {{ documentary.Year }}
                        </p>
                    </div>
                </li>
            </div>
              {% endfor %}
              {% else %} 
              <div class="col-12 col-md-12 col-sm-12">
               
                <div class="card">
                  <div class="card-header">
                    <h4>Ops....</h4>
                  </div>
                  <div class="card-body">
                    <div class="empty-state" data-height="600" style="height: 600px;">
                      <img width="499" class="img-fluid" src="{% static 'img/drawkit-full-stack-man-colour.svg' %}" alt="image">
                      <h2 class="mt-0">Pesquisa para adicionar novos Documentários podemos alcançar o servidor</h2>
                      <p class="lead">
                       Faça novas pesquisa para adiciona novos Documentários para seu catalogo de filmes.
                      </p>
                      
                    </div>
                  </div>
                </div>
              </div>
              {% endif %}
             
		
  </div>

{% endblock %}