IMDb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import  settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndesTemplateView.as_view(),name = 'index'),
    path('lancamentos/',views.LancamentosTemplateView.as_view(), name = 'lancamentos'),
    path('cartaz/',views.CartazTemplatesViews.as_view(), name = 'cartaz'),
    path('accounts/', include('accounts.urls')),
    path('documentary/', include('documentary.urls', namespace = 'documentary')),
    path('serie/', include('serie.urls', namespace = 'serie')),
    path('movie/',include('movie.urls', namespace = 'movie')),
    path('actor/', include('actor.urls', namespace = 'actor')),

    #------------------ Dashboard --------------------------------------------------------

    path('dashboard/', include('dashboard.urls', namespace = 'dashboard')),


    #------------------------ MANAGEMENT --------------------------
    path('',include('management.urls', namespace = 'management')),

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

actor/urls.py
from django.urls import path
from . import views


app_name = 'actor'


urlpatterns = [
	path('persona/', views.actors, name='index'),
	path('persona/<slug>/details/',views.details, name = 'details'),
]

movie/urls.py
from django.urls import path
from . import views 


app_name = 'movie'


urlpatterns = [
	path('manager/', views.movie_templateview, name='manager'),
	path('search/', views.index, name='search'),	
	path('<imdb_id>/details/', views.movieDetails, name='movie-details'),
	path('<imdb_id>/addtomoviewatch', views.addMoviesToWatch, name='add-movies-to-watch'),
	path('<imdb_id>/addmoviewatched', views.addMoviesWatched, name='add-movies-watched'),
	path('genre/<slug:genre_slug>', views.genres, name='genres'),
	path('<imdb_id>/rate', views.Rate, name='rate-movie'),
]

serie/urls.py
from django.urls import path
from . import views


app_name = 'serie'



urlpatterns = [
    
    path('manager/', views.serie_templateview, name='manager'),
	path('search/', views.serie_search, name='search'),	
	path('<imdb_id>/details/', views.movieDetails, name='serie-details'),
]

actor/models.py
from django.db import models

from django.utils.text import slugify
from django.urls import reverse

# Create your models here.

class Actor(models.Model):
	name = models.CharField(max_length=70, unique=True)
	picture = models.URLField(blank=True)
	slug = models.SlugField(null=True, unique=True)
	movies = models.ManyToManyField('movie.Movie', blank = True)
	series = models.ManyToManyField('serie.Serie', blank = True)
	documentarys = models.ManyToManyField('documentary.Documentary', blank = True)

	def get_absolute_url(self):
		return reverse('actors', args=[self.slug])

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.name)
		return super().save(*args, **kwargs)

actor/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import loader
from django.http import HttpResponse

from actor.models import Actor
from movie.models import Movie

# Create your views here.


def actors(request):	
	actors = Actor.objects.all()
	movies = Movie.objects.filter(Actors=actors)


	paginator = Paginator(actors, 9) # 3 posts in each page
	page = request.GET.get('page')
	try:
		paginas = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer deliver the first page
		paginas = paginator.page(1)
	except EmptyPage:
		# If page is out of range deliver last page of results
		paginas = paginator.page(paginator.num_pages)
	

	
	return render(request, 'actor/index.html',{	'paginas': paginas,'actors': actors, 'movies':movies})



def details(request, slug):
	actor = get_object_or_404(Actor, slug = slug)
	return render(request, 'actor/details.html',{'actor':actor})

actor/templates/actor/created.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% load bootstrap4 %}


{% block management %}
<div class="section-header">
    <div class="slider-outer">
        <div class="slider-inner">
            <div class="  statistic fron active" data-slider="1">
                <i class="fas fa-laptop-code"></i>
                <div class="statistic-title">Filmes</div>
                <h2 class="title-statistic-h2">Add +</h2>
                              
            </div>
        </div>
    </div>
</div>

  <div class="section-body">
      	
			<div class="dashboard-container">
				
                <h2 class="section-title">Adicionar Novos Filmes</h2>
                <p class="section-lead">
                    Skrn - Site completo com filmes lançamentos, séries em HD online dublado e legendado em HD e FullHD. 
                </p>

				<div class="row">
								
					<div class="col-12 col-md-6 col-lg-6">
						<div class="card">
						  <div class="card-header">
							<h4>Formulário</h4>
						  </div>
						  <div class="card-body">
							<div class="alert alert-info">
							  <b>Nota!</b> lançamentos de um novo filme em HD online em HD e FullHD.
							</div>            
							{# Display a form #}
							<form style = "margin-left:36px; margin-right:36px;"  action="." method="post" >
							<div style = "position:relative; right:40px;" class="card-header">
									<h4>Validação do dados  do Filme</h4>
									</div>
								{% csrf_token %}
								{% bootstrap_form form %}
								{% buttons %}
									<button type="submit" class="btn btn-primary">Criar</button>
								{% endbuttons %}
								  
							</div>
						   
						 
						</div>
					 
			  
						  </div>
					 
				
				</div><!-- close .row -->
									
			</div><!-- close .dashboard-container -->
  </div>

{% endblock %}

actor/templates/actor/details.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block management %}
<div class="section-header">
    <div class="slider-outer">
        <div class="slider-inner">
            <div class="  statistic fron active" data-slider="1">
                <i class="fas fa-info"></i>
				
                <div class="statistic-title">Persona</div>
                <h2 class="title-statistic-h2">Informações</h2>
                              
            </div>
        </div>
    </div>
</div>
<div class="section-body">
  <h2 class="section-title">Persona</h2>
  <p class="section-lead">
    As informações sobre o ator (a).
  </p>

  <div class="row mt-sm-4">
    <div class="col-12 col-md-12 col-lg-12">
      <div class="card profile-widget">
        <div class="profile-widget-header">
          <img alt="image" src="{{ actor.picture }}" class="rounded-circle profile-widget-picture">
          <div class="profile-widget-items">
            <div class="profile-widget-item">
              <div class="profile-widget-item-label">Movies</div>
              <div class="profile-widget-item-value">{{ actor.movies.count }}</div>
            </div>
            <div class="profile-widget-item">
              <div class="profile-widget-item-label">Séries</div>
              <div class="profile-widget-item-value">{{ actor.series.count }}</div>
            </div>
            <div class="profile-widget-item">
              <div class="profile-widget-item-label">Documentários</div>
              <div class="profile-widget-item-value">{{ actor.documentarys.count }}</div>
            </div>
          </div>
        </div>
        <div class="profile-widget-description">
          <div class="profile-widget-name">Name <div class="text-muted d-inline font-weight-normal"><div class="slash"></div> {{ actor.name }}</div></div>
          Ujang maman is a superhero name in <b>Indonesia</b>, especially in my family. He is not a fictional character but an original hero in my family, a hero for his children and for his wife. So, I use the name as a user in this template. Not a tribute, I'm just bored with <b>'John Doe'</b>.
          <div  class=" mt-sm-0 mt-3 mb-7 btn-movie ">
            <a  href="#" class="btn"><i class="far fa-edit"></i></a>
            <a href="#" class="btn"><i class="far fa-trash-alt"></i></a>
          </div> 
        </div> 
            
      </div>
    </div> 
    <div class="col-12 col-sm-6 col-lg-12">
      <div class="card">
        <div class="card-header">
          <h4>Movies</h4>
        </div>
        <div class="card-body">
          <div class="gallery gallery-md">
            {% for movie in actor.movies.all %}
            <a href="{% url 'movie:movie-details' movie.imdbID %}"><div class="gallery-item" data-image="{{ movie.Poster_url }}" data-title="Image 1"></div></a>
           {% endfor %}
          </div>
        </div>
      </div>
    </div>  
    <div class="col-12 col-sm-6 col-lg-12">
      <div class="card">
        <div class="card-header">
          <h4>Séries</h4>
        </div>
        <div class="card-body">
          <div class="gallery gallery-md">
            {% for series in actor.series.all %}
           <a href="{% url 'serie:serie-details' series.imdbID %}"><div class="gallery-item" data-image="{{ series.Poster_url }}" data-title="Image 1"></div></a> 
           {% endfor %}
          </div>
        </div>
      </div>
    </div>  
    <div class="col-12 col-sm-6 col-lg-12">
      <div class="card">
        <div class="card-header">
          <h4>Documentários</h4>
        </div>
        <div class="card-body">
          <div class="gallery gallery-md">
            {% for documentary in actor.documentarys.all %}
            <a href=""></a><div class="gallery-item" data-image="{{ documentary.Poster_url }}" data-title="Image 1"></div>
           {% endfor %}
          </div>
        </div>
      </div>
    </div>  
  </div>
</div>

{% endblock %}

actor/templates/actor/index.html
{% extends 'dashboard/base.html' %}
{% load static %}


{% block management %}
<div class="section-header">
    <div class="slider-outer">
        <div class="slider-inner">
            <div class="  statistic fron active" data-slider="1">
              <i class="fas fa-street-view"></i>
				
                <div class="statistic-title">Dashboard</div>
                <h2 class="title-statistic-h2">Persona</h2>
                              
            </div>
        </div>
    </div>
</div>

  <div class="section-body">
      	<h2 class="section-title">Lista de filmes adicionado</h2>
            <div class="row">
                {% if paginas %}
                {% for actor in paginas %}           
              <div class="col-12 col-md-4 col-lg-4">
                <li class="catalogo-filmes-lista-item catalogo-filmes-lista-modificado">
                    <figure class="filme-poster">
                       <a href="{% url 'actor:details' actor.slug %}"><img src="{{ actor.picture }}" alt="{{ actor.name }}" /></a> 
                        <div class="filme-poster-info">
                            <h3>{{ actor.name }}</h3>
                            <a href="{% url 'actor:details' actor.slug %}" class="filme-poster-link"
                                ><i class="fa fa-play" aria-hidden="true"></i
                            ></a>
                        </div>
                    </figure>

                    <div class="filme-sinopse">
                        <a href="{% url 'actor:details' actor.slug %}"><h3 class="filme-sinopse-titulo">{{ actor.name }}</h3></a>
                        <p class="sinopse-genero">                          
                            <a href="#" class="sinopse-genero-item">{{ movie.Type }}</a>                          
                        </p>
                        <p class="filme-nota">
                            <i class="fa fa-heart" aria-hidden="true"></i> {{ movie.Year }}
                        </p>
                    </div>
                </li>
            </div>
      
              {% endfor %}
              {% else %} 
              <div class="col-12 col-md-12 col-sm-12">
               
                <div class="card">
                  <div class="card-header">
                    <h4>Ops....</h4>
                  </div>
                  <div class="card-body">
                    <div class="empty-state" data-height="600" style="height: 600px;">
                      <img width="499" class="img-fluid" src="{% static 'img/drawkit-full-stack-man-colour.svg' %}" alt="image">
                      <h2 class="mt-0">Pesquisa para adicionar novos filmes podemos alcançar o servidor</h2>
                      <p class="lead">
                       Faça novas pesquisa para adiciona novos filmes para seu catalogo de filmes.
                      </p>
                      
                    </div>
                  </div>
                </div>
              </div>
              
              {% endif %}
             
              <nav aria-label="Page navigation example">
                <ul class="pagination">
                  {% if paginas.has_previous %}                 
                  <li class="page-item"><a class="page-link" href="?page={{ paginas.previous_page_number }}">Previous</a></li>
                  {% endif %}                  
                  <li class="page-item"><a class="page-link" href="#">{{ paginas.number }}</a></li>
                  <li class="page-item"><a class="page-link" href="#">...</a></li>
                  <li class="page-item"><a class="page-link" href="#">{{ paginas.paginator.num_pages }}</a></li>
                  {% if paginas.has_next %}                 
                  <li class="page-item"><a class="page-link" href="?page={{ paginas.next_page_number }}">Next</a></li>
                {% endif %}                 
                </ul>
              </nav>

{% endblock %}

actor/templates/actor/search.html
{% extends 'dashboard/base.html' %}
{% load static %}


{% block management %}
<div class="section-header">
    <div class="slider-outer">
        <div class="slider-inner">
            <div class="  statistic fron active" data-slider="1">
                <i class="fas fa-search"></i>
				
                <div class="statistic-title">Filmes</div>
                <h2 class="title-statistic-h2">Search</h2>
                              
            </div>
        </div>
    </div>
</div>

  <div class="section-body">
      	<h2 class="section-title">Pesquisando Novo filmes para adicionar</h2>
            <div class="row">
                {% if movie_data.Search %}
                {% for movie in movie_data.Search %}           
              <div class="col-12 col-md-4 col-lg-4">
                <li class="catalogo-filmes-lista-modificado>
                    <figure class="filme-poster">
                       <a href="{% url 'movie:movie-details' movie.imdbID %}"><img src="{{ movie.Poster }} alt="img" /></a> 
                        <div class="filme-poster-info">
                            <h3>{{ movie.title}}</h3>
                            <a href="{% url 'movie:movie-details' movie.imdbID %}" class="filme-poster-link"
                                ><i class="fa fa-play" aria-hidden="true"></i
                            ></a>
                        </div>
                    </figure>

                    <div class="filme-sinopse">
                        <a href="{% url 'movie:movie-details' movie.imdbID %}"><h3 class="filme-sinopse-titulo">{{ movie.Title }}</h3></a>
                        <p class="sinopse-genero">                          
                            <a href="#" class="sinopse-genero-item">{{ movie.Type }}</a>                          
                        </p>
                        <p class="filme-nota">
                            <i class="fa fa-heart" aria-hidden="true"></i> {{ movie.Year }}
                        </p>
                    </div>
                </li>
            </div>
              {% endfor %}
              {% else %} 
              <div class="col-12 col-md-12 col-sm-12">
               
                <div class="card">
                  <div class="card-header">
                    <h4>Ops....</h4>
                  </div>
                  <div class="card-body">
                    <div class="empty-state" data-height="600" style="height: 600px;">
                      <img width="499" class="img-fluid" src="{% static 'img/drawkit-full-stack-man-colour.svg' %}" alt="image">
                      <h2 class="mt-0">Pesquisa para adicionar novos filmes podemos alcançar o servidor</h2>
                      <p class="lead">
                       Faça novas pesquisa para adiciona novos filmes para seu catalogo de filmes.
                      </p>
                      
                    </div>
                  </div>
                </div>
              </div>
              {% endif %}
             
		
  </div>

{% endblock %}

actor/templates/actor/update.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% load bootstrap4 %}


{% block management %}
<div class="section-header">
    <div class="slider-outer">
        <div class="slider-inner">
            <div class="  statistic fron active" data-slider="1">
                <i class="far fa-edit"></i>
				
                <div class="statistic-title">Filmes</div>
                <h2 class="title-statistic-h2">Atualizações</h2>
                              
            </div>
        </div>
    </div>
</div>

  <div class="section-body">
      	
			<div class="dashboard-container">
				
                <h2 class="section-title">Atualizar o Filmes: <span>{{ object }}</span> </h2>
                <p class="section-lead">
                    Skrn - Site completo com filmes lançamentos, séries em HD online dublado e legendado em HD e FullHD. 
                </p>

				<div class="row">
								
					<div class="col-12 col-md-6 col-lg-6">
						<div class="card">
						  <div class="card-header">
							<h4>Formulário</h4>
						  </div>
						  <div class="card-body">
							<div class="alert alert-info">
							  <b>Nota!</b> lançamentos de um novo filme em HD online em HD e FullHD.
							</div>            
							{# Display a form #}
							<form style = "margin-left:36px; margin-right:36px;"  action="." method="post" >
							<div style = "position:relative; right:40px;" class="card-header">
									<h4>Validação do dados  do Filme</h4>
									</div>
								{% csrf_token %}
								{% bootstrap_form form %}
								{% buttons %}
									<button type="submit" class="btn btn-primary">Atualizar</button>
								{% endbuttons %}
								  
							</div>
						   
						 
						</div>
					 
			  
						  </div>
					 
				
				</div><!-- close .row -->
									
			</div><!-- close .dashboard-container -->
  </div>

{% endblock %}