IMDb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import  settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndesTemplateView.as_view(),name = 'index'),
    path('lancamentos/',views.LancamentosTemplateView.as_view(), name = 'lancamentos'),
    path('cartaz/',views.CartazTemplatesViews.as_view(), name = 'cartaz'),
    path('accounts/', include('accounts.urls')),
    path('documentary/', include('documentary.urls', namespace = 'documentary')),
    path('serie/', include('serie.urls', namespace = 'serie')),
    path('movie/',include('movie.urls', namespace = 'movie')),
    path('actor/', include('actor.urls', namespace = 'actor')),

    #------------------ Dashboard --------------------------------------------------------

    path('dashboard/', include('dashboard.urls', namespace = 'dashboard')),


    #------------------------ MANAGEMENT --------------------------
    path('',include('management.urls', namespace = 'management')),

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

management/urls.py
from django.urls import path
from . import views


app_name = 'management'




urlpatterns = [

    path('management/index/',views.ManagementTemplateView.as_view(),name = 'index'),
    path('management/filmes/',views.FilmesTemplateView.as_view(), name = 'filmes_manager'),
    path('management/search/', views.movie_management, name = 'search'),
    path('<imdb_id>/', views.movieDetails, name = 'movie-details'),
   
    
]

management/models.py
from django.db import models

# Create your models here.

management/views.py
from django.views.generic import View, ListView, TemplateView, DetailView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from movie.models import Movie, Genre, Rating, Review
from django.core.paginator import Paginator
from django.utils.text import slugify
from django.template import loader
from django.db.models import Avg
from django.urls import reverse
from actor.models import Actor
import requests
# Create your views here.





class ManagementTemplateView(TemplateView):
    template_name = 'management/index.html'



class FilmesTemplateView(TemplateView):
    template_name = 'management/filmes.html'



def movie_management(request):

    query  = request.GET.get('search', None)
    if query is not None:
        url  = 'http://www.omdbapi.com/?apikey=2d2a4142&s='+ query 
        response = requests.get(url)
        movie_data = response.json() 
        return render(request,'management/search.html', {'query':query,'movie_data':movie_data})

    return render(request, 'management/search.html')
 





def movieDetails(request, imdb_id):

	if Movie.objects.filter(imdbID=imdb_id).exists():
		movie_data = Movie.objects.get(imdbID=imdb_id)
		reviews = Review.objects.filter(movie=movie_data)
		reviews_avg = reviews.aggregate(Avg('rate'))
		reviews_count = reviews.count()
		our_db = True

		context = {
			'movie_data': movie_data,
			'reviews': reviews,
			'reviews_avg': reviews_avg,
			'reviews_count': reviews_count,
			'our_db': our_db,
		}

	else:
		url = 'http://www.omdbapi.com/?apikey=2d2a4142&i=' + imdb_id
		response = requests.get(url)
		movie_data = response.json()

		#Inject to our database bellow:

		rating_objs = []
		genre_objs = []
		actor_objs = []

		#For the actors
		actor_list = [x.strip() for x in movie_data['Actors'].split(',')]

		for actor in actor_list:
			a, created = Actor.objects.get_or_create(name=actor)
			actor_objs.append(a)

		#For the Genre or categories
		genre_list = list(movie_data['Genre'].replace(" ", "").split(','))

		for genre in genre_list:
			genre_slug = slugify(genre)
			g, created = Genre.objects.get_or_create(title=genre, slug=genre_slug)
			genre_objs.append(g)

		#For the Rate
		for rate in movie_data['Ratings']:
			r, created = Rating.objects.get_or_create(source=rate['Source'], rating=rate['Value'])
			rating_objs.append(r)

		if movie_data['Type'] == 'movie':
			m, created = Movie.objects.get_or_create(
				Title=movie_data['Title'],
				Year=movie_data['Year'],
				Rated=movie_data['Rated'],
				Released=movie_data['Released'],
				Runtime=movie_data['Runtime'],
				Director=movie_data['Director'],
				Writer=movie_data['Writer'],
				Plot=movie_data['Plot'],
				Language=movie_data['Language'],
				Country=movie_data['Country'],
				Awards=movie_data['Awards'],
				Poster_url=movie_data['Poster'],
				Metascore=movie_data['Metascore'],
				imdbRating=movie_data['imdbRating'],
				imdbVotes=movie_data['imdbVotes'],
				imdbID=movie_data['imdbID'],
				Type=movie_data['Type'],
				DVD=movie_data['DVD'],
				BoxOffice=movie_data['BoxOffice'],
				Production=movie_data['Production'],
				Website=movie_data['Website'],
				)
			m.Genre.set(genre_objs)
			m.Actors.set(actor_objs)
			m.Ratings.set(rating_objs)

		else:
			m, created = Movie.objects.get_or_create(
				Title=movie_data['Title'],
				Year=movie_data['Year'],
				Rated=movie_data['Rated'],
				Released=movie_data['Released'],
				Runtime=movie_data['Runtime'],
				Director=movie_data['Director'],
				Writer=movie_data['Writer'],
				Plot=movie_data['Plot'],
				Language=movie_data['Language'],
				Country=movie_data['Country'],
				Awards=movie_data['Awards'],
				Poster_url=movie_data['Poster'],
				Metascore=movie_data['Metascore'],
				imdbRating=movie_data['imdbRating'],
				imdbVotes=movie_data['imdbVotes'],
				imdbID=movie_data['imdbID'],
				Type=movie_data['Type'],
				totalSeasons=movie_data['totalSeasons'],
				)

			m.Genre.set(genre_objs)
			m.Actors.set(actor_objs)
			m.Ratings.set(rating_objs)


		for actor in actor_objs:
			actor.movies.add(m)
			actor.save()

		m.save()
		our_db = False

		context = {
			'movie_data': movie_data,
			'our_db': our_db,
		}

	template = loader.get_template('management/movie_details.html')

	return HttpResponse(template.render(context, request))

management/templates/management/filmes.html
{% extends 'management/base.html' %}
{% load static %}



{% block management %}
<div class="section-header">
    <div class="slider-outer">
        <div class="slider-inner">
            <div class="  statistic fron active" data-slider="1">
                <i class="fas fa-film"></i>
				
                <div class="statistic-title">Management</div>
                <h2 class="title-statistic-h2">Filmes  </h2>
                              
            </div>
        </div>
    </div>
</div>
    <div class="section-body">      	
		<div class="dashboard-container">
            <h2 class="section-title">Informações do Filmes: <span>{{ object }}</span> </h2>
            <p class="section-lead">
                Skrn - Site completo com filmes lançamentos, séries em HD online dublado e legendado em HD e FullHD. 
            </p>

            <div class="row">
                <div class="col-4 col-md-4 col-lg-4">
                  <article class="article article-style-">
                    <div class="article-header">
                      <div  class="article-image" data-background="{{ object.images }}">
                      </div>
                    </div>
                   
                  </article>
                </div>              
                
              </div>			
	    </div><!-- close .row -->									
	</div><!-- close .dashboard-container -->
  

{% endblock %}

management/templates/management/movie_details.html
{% extends 'management/base.html' %}
{% load static %}


{% block management %}
<div class="section-header">
    <div class="slider-outer">
        <div class="slider-inner">
            <div class="  statistic fron active" data-slider="1">
                <i class="fas fa-info"></i>
				
                <div class="statistic-title">Filmes</div>
                <h2 class="title-statistic-h2">Informações</h2>
                              
            </div>
        </div>
    </div>
</div>
    <div class="section-body">      	
		<div class="dashboard-container">
            <h2 class="section-title">Informações do Filmes: <span>{{ object }}</span> </h2>
            <p class="section-lead">
                Skrn - Site completo com filmes lançamentos, séries em HD online dublado e legendado em HD e FullHD. 
            </p>
            <div class="row">
                <div class="col-12 col-md-4 col-lg-4">
                  <article class="article article-style-">
                    <div class="article-header">
                    {% if our_db is True%}
                    <div  class="article-image" data-background="{{ movie_data.Poster_url }}"></div>
                    {% else %}
                    <div  class="article-image" data-background="{{ movie_data.Poster }}"></div>
                    {% endif %}                  
                    </div>                   
                  </article>
                </div>
                <div class="col-12 col-sm-12 col-lg-7">
                    <div class="card author-box card-warning">
                      <div class="card-body">                        
                        <div >
                          <div class="author-box-name">
                            <a href="#">{{ movie_data.Title }}</a>
                        </div>
                        <div class="author-box-job"><li><span>Tipo:</span> <a href="#">{{ movie_data.Type }}</a></li></div>
                        <div class="author-box-job"><li><span>Descrição:</span> <a href="#">{{ movie_data.Plot }}</a></li></div>
                        <div class="author-box-job"><li><span>Ano de Lançamento:</span> <a href="#">{{ movie_data.Year }}</a></li></div>
                        <div class="author-box-job"><li><span>Avaliado:</span> <a href="#">{{ movie_data.Rated }}</a></li></div>
                        <div class="author-box-job"><li><span>Data de Lançamento:</span> <a href="#">{{ movie_data.Released }}</a></li></div>
                        <div class="author-box-job"><li><span>Runtime:</span> <a href="#">{{ movie_data.Runtime }}</a></li></div>

          
                          {% if our_db is True %}
                          <div class="author-box-job"><li ><span>Categorias:{% for genre in movie_data.Genre.all %}</span> <a href="#">Ação,</a> <a href="#">{{ genre }},</a>{% endfor %}</li></div>
                          {% else %}
                          <div class="author-box-job"><li ><span>Categorias:</span><a href="#">{{ movie_data.Genre }},</a></li></div>
                          {% endif %}
                          <div class="author-box-job"><li><span>Diretores:</span> <a href="#">{{ movie_data.Director }}</a></li></div>
                          <div class="author-box-job"><li><span>Escritor(a):</span> <a href="#">{{ movie_data.Writer }}</a></li></div>
                          {% if our_db is True %}
                          <div class="author-box-job"><li><span>Atores:{% for actor in movie_data.Actors.all %}</span> <a href="#">{{ actor }}</a>{% endfor %}</li></div>
                          {% else %}
                          <div class="author-box-job"><li><span>Atores:</span> <a href="#">{{ movie_data.Actors }}</a></li></div>
                          {% endif %}
                          <div class="author-box-job"><li><span>Linguagem:</span> <a href="#">{{ movie_data.Language }}</a></li></div>
                          <div class="author-box-job"><li><span>País:</span> <a href="#">{{ movie_data.Country }}</a></li></div>
                          <div class="author-box-job"><li><span>Prêmios:</span> <a href="#">{{ movie_data.Awards }}</a></li></div>
                         
                          <div class="author-box-description">
                            <p>{{ movie.Overview}}</p>
                          </div>                         
                            <br>                                               
                          <ul class="list-unstyled user-progress list-unstyled-border list-unstyled-noborder">                                                                          
                             <li class="media">
                                {% if  our_db is True %}
                                {% for movie in movie_data.Ratings.all %}   
                                {% if movie.source == 'Internet Movie Database' %}                 
                                <div class="media-items">
                                  <div class="media-item">
                                    <div class="media-value">{{ movie.rating }}</div>
                                    <div class="media-label">{{ movie.source }} </div>                                   
                                </div>
                                  </div>
                                  {% elif movie.source == 'Rotten Tomatoes' %} 
                                  <div class="media-items"> 
                                  <div class="media-item">
                                    <div class="media-value">{{ movie.rating }}</div>
                                    <div class="media-label">{{ movie.source }} </div>
                                  </div>
                                  </div>
                                  {% else %} 
                                 <div class="media-items"> 
                                  <div class="media-item">
                                    <div class="media-value">{{ movie.rating }}</div>
                                    <div class="media-label">{{ movie.source }} </div>
                                  </div>
                                 </div>
                                 {% endif %}
                                 {% endfor %}
                                 {% else %}
                        </li>    
                            <li class="media">                            
                                <div class="media-body">
                                    <img src="" alt="">
                                  <div class="media-title">{{ movie_data.Ratings.0.Source }} </div>
                                  <div class="text-job text-muted">{{ movie_data.Ratings.0.Value }}</div>
                                </div>
                                <div class="media-progressbar">
                                  <div class="progress-text"></div>                                 
                                </div>                             
                              </li> 
                              <li class="media">                            
                                <div class="media-body">
                                    <img src="" alt="">
                                  <div class="media-title">{{ movie_data.Ratings.1.Source }} </div>
                                  <div class="text-job text-muted">{{ movie_data.Ratings.1.Value }}</div>
                                </div>
                                <div class="media-progressbar">
                                  <div class="progress-text"></div>                                 
                                </div>                             
                              </li> 
                              <li class="media">                            
                                <div class="media-body">
                                    <img src="" alt="">
                                  <div class="media-title">{{ movie_data.Ratings.2.Source }} </div>
                                  <div class="text-job text-muted">{{ movie_data.Ratings.2.Value }}</div>
                                </div>
                                <div class="media-progressbar">
                                  <div class="progress-text"></div>                                 
                                </div>                             
                              </li> 
                            {% endif %}                           
                          </ul>                          
                          <div class="author-box-job"><li><span>Box Office:</span> <a href="#">{{ movie_data.BoxOffice }}</a></li></div>
                          <div class="author-box-job"><li><span>imdb Votes:</span> <a href="#">{{ movie_data.omdbVotes }}</a></li></div>
                          <div class="author-box-job"><li><span>Production:</span> <a href="#">{{ movie_data.Production }}</a></li></div>
                          <div  class=" mt-sm-0 mt-3 btn-movie ">
                            <a  href="#" class="btn"><i class="far fa-edit"></i></a>
                            <a href="#" class="btn"><i class="far fa-trash-alt"></i></a>
                          </div>                          
                        </div>
                      </div>
                    </div>                   
                  </div>            
              </div>			
	    </div><!-- close .row -->									
	</div><!-- close .dashboard-container -->
  

{% endblock %}

management/templates/management/search.html
{% extends 'management/base.html' %}
{% load static %}



{% block management %}
<div class="section-header">
    <div class="slider-outer">
        <div class="slider-inner">
            <div class="  statistic fron active" data-slider="1">
                <i class="fas fa-search"></i>
				
                <div class="statistic-title">Filmes</div>
                <h2 class="title-statistic-h2">Search</h2>
                              
            </div>
        </div>
    </div>
</div>
    <div class="section-body">      	
		<div class="dashboard-container">
            <h2 class="section-title">Informações do Filmes: <span>{{ object }}</span> </h2>
            <p class="section-lead">
                Skrn - Site completo com filmes lançamentos, séries em HD online dublado e legendado em HD e FullHD. 
            </p>

            <div class="row">
                {% for movie in movie_data.Search %}
                <div class="col-14 col-md-4 col-lg-4">
                  <article class="article article-style-">
                    <figure class="filme-poster">
                       <a href="{% url 'management:movie-details' movie.imdbID %}"><img src="{{ movie.Poster }}" alt="" /></a>
                        <div class="filme-poster-info">
                            <h3>{{ movie.title }}</h3>
                            <a href="#" class="filme-poster-link"
                                ><i class="fa fa-play" aria-hidden="true"></i
                            ></a>
                        </div>
                    </figure>

                    <div class="filme-sinopse">
                        <h3 class="filme-sinopse-titulo">{{ movie.Title }}</h3>
                        <p class="sinopse-genero">                           
                            <a href="#" class="sinopse-genero-item"> {{ movie.Type}}</a>
                        </p>
                        <p class="filme-nota">
                            <i class="fa fa-heart" aria-hidden="true"></i> {{ movie.Year}}
                        </p>
                    </div>
                  </article>
                </div>              
                {% endfor %}
              </div>			
	    </div><!-- close .row -->									
	</div><!-- close .dashboard-container -->
  
  
{% endblock %}